version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "20:00"
    groups:
      aws-sdk:
        patterns:
          - github.com/aws/aws-sdk-go-v2
          - github.com/aws/aws-sdk-go-v2/*
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
