services:
  localstack:
    container_name: "rainbow-localstack"
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN- }
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DNS_LOCAL_NAME_PATTERNS='.*cloudfront\.net'
      - CLOUDFRONT_STATIC_PORTS= 1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "data:/home/localstack/data"
volumes:
  data:
