AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Description: "Lambda Batch"

Parameters:
  Environment:
    Type: String
    Description: "Runtime Environment"
    Default: "development"

Resources:
  LambdaBatch:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: "Lambda Batch"
      Handler: "handler"
      Runtime: provided.al2
      Architectures: [arm64]
      Role: !GetAtt LambdaBatchRole.Arn
      CodeUri: ./
      MemorySize: 128
      Timeout: 5
      Environment:
        Variables:
          APP_ENV: !Ref Environment
      Events:
        Schedule:
          Type: Schedule
          # To declare this entity in your AWS Serverless Application Model (AWS SAM) template.
          # Ref. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventsource.html
          Properties:
            Name: sample-schedule-event
            Schedule: rate(1 minute)

  LambdaBatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"

  LambdaLogGroup:
    Type: "AWS::Logs::LogGroup"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LambdaBatch}"
      RetentionInDays: 7
        
