name: CloudFormation Guard Action

on:
  push:

jobs:
  cfn-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: grolston/guard-action@main
      with:
        data_directory: './cloudformation/'
        rule_set: "wa-Reliability-Pillar"

    - uses: grolston/guard-action@main
      with:
        data_directory: './cloudformation/'
        rule_set: "wa-Security-Pillar"