name: CloudFormation Guard Action

on:
  push:

jobs:
  cfn-guard:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

   # TODO: https://github.com/grolston/guard-action/issues/2
   # - uses: grolston/guard-action@main
   #   with:
   #     data_directory: './cloudformation/'
   #     rule_set: "wa-Reliability-Pillar"

   # - uses: grolston/guard-action@main
   #   with:
   #     data_directory: './cloudformation/'
   #     rule_set: "wa-Security-Pillar"
