name: Deploy to LocalStack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false

      - name: Setup localstack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        # https://docs.localstack.cloud/user-guide/ci/github-actions/
        run: |
          docker compose up -d
          echo "Waiting for LocalStack startup..."
          sleep 30
          echo "Startup complete" 

      - name: Deploy to LocalStack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: make deploy
