name: LinuxUnitTest

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit test (linux)

    strategy:
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1"
          check-latest: true

      - name: Setup localstack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        # https://docs.localstack.cloud/user-guide/ci/github-actions/
        run: |
          docker compose up -d
          echo "Waiting for LocalStack startup..."
          sleep 30
          echo "Startup complete"   

      - name: Download dependencies
        run: go mod download

      - name: Set up AWS credentials
        run: |
          echo "[default]" > $HOME/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials

      - name: Set up AWS config
        run: |
          echo "[default]" > $HOME/.aws/config
          echo "region=us-east-1" >> $HOME/.aws/config
          echo "output=json" >> $HOME/.aws/config
          echo "endpoint_url=http://localhost:4566" >> $HOME/.aws/config

      - uses: nao1215/actions-hottest@v1
        with:
          args: '-cover -coverpkg=./... -coverprofile=coverage.out ./...'

      - uses: k1LoW/octocov-action@v0
