name: MacUnitTest

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit_test:
    name: Unit test (mac)

    strategy:
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1"
          check-latest: true

      - name: Setup localstack
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        # https://docs.localstack.cloud/user-guide/ci/github-actions/
        run: |
          docker compose up -d
          echo "Waiting for LocalStack startup..."
          sleep 30
          echo "Startup complete"   

      - name: Download dependencies
        run: go mod download

      - name: Set up AWS config and AWS credentials
        run: |
          mkdir -p "$HOME/.aws"
          echo -e "[default]\naws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}\naws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" > "$HOME/.aws/credentials"
          echo -e  "[default]\nregion=us-east-1\noutput=json\nendpoint_url=http://localhost:4566" > "$HOME/.aws/config"

      - name: Run unit test
        run: |
          go mod download
          go test -race -v ./...
